### ISSUE TITLE
CNCF TechDocs Analysis issues tracker

### ISSUE THREAD

**Issue by nate-double-u** [cncf/techdocs#221]
## Backstage
- [ ] https://github.com/backstage/backstage/issues/21893
- [ ] https://github.com/backstage/backstage/issues/21828
- [ ] https://github.com/backstage/backstage/issues/21913
- [ ] https://github.com/backstage/backstage/issues/21915
- [ ] https://github.com/backstage/backstage/issues/21916
- [ ] https://github.com/backstage/backstage/issues/21920
- [ ] https://github.com/backstage/backstage/issues/21921
- [ ] https://github.com/backstage/backstage/issues/21922
- [ ] https://github.com/backstage/backstage/issues/21923
- [ ] https://github.com/backstage/backstage/issues/21925
- [ ] https://github.com/backstage/backstage/issues/21926
- [ ] https://github.com/backstage/backstage/issues/21942
- [ ] https://github.com/backstage/backstage/issues/21943
- [ ] https://github.com/backstage/backstage/issues/21944
- [ ] https://github.com/backstage/backstage/issues/21945
- [ ] https://github.com/backstage/backstage/issues/21946
- [ ] https://github.com/backstage/backstage/issues/22001
- [ ] https://github.com/backstage/backstage/issues/22002
- [ ] https://github.com/backstage/backstage/issues/22003

## etcd
- [ ] https://github.com/etcd-io/website/issues/766
- [ ] https://github.com/etcd-io/website/issues/765
- [ ] https://github.com/etcd-io/website/issues/767
- [ ] https://github.com/etcd-io/website/issues/768
- [ ] https://github.com/etcd-io/website/issues/769
- [ ] https://github.com/etcd-io/website/issues/770
- [ ] https://github.com/etcd-io/website/issues/771
- [ ] https://github.com/etcd-io/website/issues/772
- [ ] https://github.com/etcd-io/website/issues/773
- [ ] https://github.com/etcd-io/website/issues/780
- [ ] https://github.com/etcd-io/website/issues/781
- [ ] https://github.com/etcd-io/website/issues/782
- [ ] https://github.com/etcd-io/website/issues/783
- [ ] https://github.com/etcd-io/website/issues/784
- [ ] https://github.com/etcd-io/website/issues/786

## in-toto
- [ ] https://github.com/in-toto/docs/issues/85
- [ ] https://github.com/in-toto/docs/issues/86
- [ ] https://github.com/in-toto/docs/issues/87
- [ ] https://github.com/in-toto/docs/issues/88
- [ ] https://github.com/in-toto/docs/issues/89
- [ ] https://github.com/in-toto/docs/issues/90
- [ ] https://github.com/in-toto/docs/issues/91
- [ ] https://github.com/in-toto/docs/issues/92

**Comment by MANISH-K-07** [comment]
@nate-double-u , I see the help wanted label here. I have attached a short overview of my intro at https://github.com/cncf/techdocs/issues/162#issuecomment-2118821883
Can I help with the assessments?

**Comment by nate-double-u** [comment]
I believe any of these project would welcome help @MANISH-K-07. I'd suggest heading over to one of the projects you're interested in, checkout their contributing info, and say hello!

**Comment by MANISH-K-07** [comment]
Sure, will go through the projects and find an issue that spikes my interest :)
