### ISSUE TITLE
24Q1-Q4 planning and activity log for Patrice

### ISSUE THREAD

**Issue by chalin** [cncf/techdocs#227]
# Main tasks

### Planning and tracking

- [x] https://github.com/open-telemetry/opentelemetry.io/issues/3739
- [x] https://github.com/open-telemetry/opentelemetry.io/issues/3918
- [x] https://github.com/open-telemetry/opentelemetry.io/issues/4082

### 2024 contribution highlights:

- **Internationalization**:
  - I lead the infrastructure development and localization-team support for i18n. [PR list TBC]
  - Tooling, layouts, and guidelines will be reusable in other projects. 
  - As a result of this, and the dedication of our i18n teams, **OTel documentation is now available in 6 locales**: English, French, Spanish, Brazilian, Japanese, and Chinese!
- **Contributor experience** improvements: through improved tooling and scripts, as well as updates to [Contributing] guidelines, in particular: I'm the main author of the [Localization] contributing guidelines.
- **Infrastructure** support and improvements, including:
  - **Reduced build times** especially given the full docs build required for 6 locales. For a full list of PRs, see [PR list TBC].
- Dark-mode support

[Contributing]: https://opentelemetry.io/docs/contributing/
[Localization]: https://opentelemetry.io/docs/contributing/localization/

## 2. [Docsy] steering committee and Docsy-related contributions:

- [x] Created basic version of a much needed CNCF [docsy-starter](https://github.com/chalin/docsy-starter).
    - Successfully used as a base for the migration of two CNCF project websites to the use of Hugo + Docsy: theupdateframework.io and in-toto.io. For details see the next section below
- [x] Wrote blog post: [Docsy 2024 Review: Adoptions and Enhancements](https://www.docsy.dev/blog/2024/year-in-review/)
- [x] [Docsy 0.11.0](https://github.com/google/docsy/releases/tag/v0.11.0) release, [reintroduces Right-To-Left (RTL) language support #1442](https://github.com/google/docsy/issues/1442)!
- [x]  Docsy 0.10.0:
  - [x] Blog [Docsy 0.10.0 release report](https://www.docsy.dev/blog/2024/0.10.0/)
  - [x] https://github.com/google/docsy/issues/1812
    - [x] https://github.com/google/docsy/issues/1528
    - [x] https://github.com/google/docsy/issues/331
- [x]  Blog [Docsy 0.9.0 release report](https://www.docsy.dev/blog/2024/0.9.0/)
- [All my issues and PRs](https://github.com/google/docsy/issues?q=author%3Achalin)
- [My open issues and PRs](https://github.com/google/docsy/issues?q=author%3Achalin+is%3Aopen)

## 3. Website improvements for other CNCF projects - upgrades to using Docsy

- [x] [theupdateframework.io: New and improved Docsy-based version of the website #105](https://github.com/theupdateframework/theupdateframework.io/pull/105)
- [ ] [kubernetes/website](https://github.com/kubernetes/website) - contributing to the following Docsy-upgrade issues:
    [Align with upstream Docsy · Issue #41171 · kubernetes/website](https://github.com/kubernetes/website/issues/41171),
    [Update theme/docsy step by step to the latest docsy #44002](https://github.com/kubernetes/website/issues/44002), and
    and [Bootstrap and Font Awesome (as part of Docsy) are deprecated · Issue #32905 · kubernetes/website](https://github.com/kubernetes/website/issues/32905)
  - [ ]  [Upgrade to Docsy 0.5.1 via NPM module #48812](https://github.com/kubernetes/website/pull/48812) - PR author
  - [x] [Bump Docsy to 0.3.x #48721](https://github.com/kubernetes/website/pull/48721) - PR reviewer
- [ ] in-toto: [Migrate website to use the Docsy theme #76](https://github.com/in-toto/in-toto.io/issues/76)
    - [ ] https://github.com/in-toto/in-toto.io/pull/86 
- [ ] Assess https://github.com/jaegertracing/documentation/issues/746

## 4. LF mentoring 2024/06-08

- [My mentorships panel](https://mentorship.lfx.linuxfoundation.org/#my-mentorships)
- [x] [in-toto](https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2024/02-Jun-Aug#in-toto)
  - Project entry: [Documentation Boost!](https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2024/02-Jun-Aug#documentation-boost)
  - https://github.com/cncf/mentoring/pull/1224
- [x] [TUF](https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2024/02-Jun-Aug#tuf)
  - Website: [theupdateframework.io](https://theupdateframework.io/), [repo](https://github.com/theupdateframework/theupdateframework.io)
  - Project entry: [Documentation assessment and improvements](https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2024/02-Jun-Aug#tuf)
  - https://github.com/cncf/mentoring/pull/1225
  - #162
  - My finalization of the project: [New and improved Docsy-based version of the website #105](https://github.com/theupdateframework/theupdateframework.io/pull/105)
- LF ID account merge request: https://jira.linuxfoundation.org/plugins/servlet/desk/portal/4/SUPPORT-27206

## 5. Analytics and related tasks

- [x] https://github.com/open-telemetry/opentelemetry.io/issues/4017
- [x] Help [kubewarden.io](https://www.kubewarden.io/) migrate to GA4
  - [x] https://cncfservicedesk.atlassian.net/browse/CNCFSD-2256
  - [x] https://github.com/kubewarden/kubewarden.io/pull/223
- [x] PipeCD
  - [x] https://cncfservicedesk.atlassian.net/browse/CNCFSD-1859
- [x] [[SANDBOX PROJECT ONBOARDING] Logging Operator](https://github.com/cncf/sandbox/issues/151)
  - [x] https://cncfservicedesk.atlassian.net/browse/CNCFSD-2325
  - [x] [Google analytics 4 (GA4): configure CNCF ID cncf/toc#244](https://github.com/kube-logging/kube-logging.github.io/pull/244)
- [ ] cncf/techdocs#151
- [ ] cncf/techdocs#167

## 6. Other

- [x] Techdocs
  - [x] cncf/techdocs#229
- [x] Doc analyses: mentor and reviewer of [TUF analysis](https://github.com/cncf/techdocs/tree/main/analyses/0012-TUF)
- cncf/techdocs#197
  https://github.com/open-telemetry/opentelemetry.io/issues/3463 
- OKRs - [none set for 2024](https://github.com/cncf/workflow/issues?q=is%3Aopen+assignee%3Achalin+label%3Aokr-2024)

### Previous/next

- cncf/techdocs#166
- #282

[Docsy]: https://github.com/google/docsy
[OpenTelemetry]: https://github.com/open-telemetry/opentelemetry.io

**Comment by chalin** [comment]
# [WIP] Main 2024 contributions in review

## **[OpenTelemetry]**

- **Internationalization**:
  - I lead the infrastructure development and localization-team support for i18n. [PR list TBC]
  - As a result of this, and the dedication of our i18n teams, OTel documentation is now available in 6 locales: English, French, Spanish, Brazilian, Japanese, and Chinese!
- **Contributor experience** improvements: through improved tooling and scripts, as well as updates to [Contributing] guidelines, in particular: I'm the main author of the [Localization] contributing guidelines.
- **Infrastructure** support and improvements, including **reduced build times** especially given the full docs build required for 6 locales. For a full list of PRs, see [PR list TBC].

[Contributing]: https://opentelemetry.io/docs/contributing/
[Docsy]: https://github.com/google/docsy
[Localization]: https://opentelemetry.io/docs/contributing/localization/
[OpenTelemetry]: https://github.com/open-telemetry/opentelemetry.io
