### ISSUE TITLE
24Q2 planning and activity log for Uche

### ISSUE THREAD

**Issue by thisisobate** [cncf/techdocs#228]
Main tasks:

- [x] [Keda docs improvement](https://github.com/orgs/kedacore/projects/5) 
  - [x] [Improve scaler catalog to be more user-friendly](https://github.com/kedacore/keda-docs/issues/412)
  - [x] [Provide versioning for our FAQ](https://github.com/kedacore/keda-docs/issues/935)
  - [x] [Run Hugo-output audit](https://github.com/kedacore/keda-docs/issues/664)
- [x] [Encourage more projects to use Artifact Hub](https://github.com/cncf/techdocs/issues/213)

**Comment by thisisobate** [comment]
@nate-double-u

**Comment by thisisobate** [comment]
https://github.com/kedacore/keda-docs/issues/935 is placed on hold for now until https://github.com/kedacore/keda-docs/pull/1389 is merged.
